# Build custom Jenkins image
docker build -t jenkins-with-docker -f Dockerfile.jenkins .

# Stop and remove old Jenkins
docker stop jenkins
docker rm jenkins

# Run new Jenkins with Docker support
docker run -d \
  --name jenkins \
  -p 8080:8080 -p 50000:50000 \
  -v jenkins_home:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /Users/emmanuelmuchiri/Documents/Kulana/CBG/CI_CD:/host_ci_cd \
  jenkins-with-docker
